# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 640)
        Dialog.setMinimumSize(QtCore.QSize(480, 640))
        Dialog.setStyleSheet("#Dialog{\n"
"    background: #1D1B26;\n"
"}")
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 51))
        self.comboBox.setStyleSheet("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.setPlaceholderText("Выбери себя из списка...")
        self.comboBox.setStyleSheet("font-size : 14px")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)
        self.startButton = QtWidgets.QPushButton(Dialog)
        self.startButton.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.startButton.setFont(font)
        self.startButton.setStyleSheet("#startButton{\n"
"    text-decoration: none;\n"
"  display: inline-block;\n"
"  width: 140px;\n"
"  height: 45px;\n"
"  line-height: 45px;\n"
"  border-radius: 45px;\n"
"  margin: 10px 20px;\n"
"  font-family: \'Montserrat\', sans-serif;\n"
"  font-size: 11px;\n"
"  text-transform: uppercase;\n"
"  text-align: center;\n"
"  letter-spacing: 3px;\n"
"  font-weight: 600;\n"
"  color: #524f4e;\n"
"  background: #2EE59D;\n"
"  box-shadow: 0 8px 15px rgba(0, 0, 0, .1);\n"
"  transition: .3s;\n"
"}\n"
"\n"
"#startButton:hover{\n"
"    background: #45AC82;\n"
"  box-shadow: 0 15px 20px rgba(46, 229, 157, .4);\n"
"  color: white;\n"
"  transform: translateY(-7px);\n"
"}\n"
"\n"
"#startButton:pressed{\n"
"    background: #0F955F;\n"
"}")
        self.startButton.setObjectName("startButton")
        self.gridLayout_2.addWidget(self.startButton, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Code Tester", "Code Tester"))
        self.startButton.setText(_translate("Dialog", "Начать"))
        self.label.setText(_translate("Dialog", "Выбери себя из списка и нажми \"Начать\""))
