# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qsci import QsciScintilla, QsciLexerPython


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 640)
        MainWindow.setStyleSheet("background: #1D1B26")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("background-color: #1D1B20 ")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.verticalLayout.addWidget(self.textBrowser_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.checkButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.checkButton.setFont(font)
        self.checkButton.setStyleSheet("#checkButton{\n"
"    color:white;\n"
"    font-weight: bold;\n"
"    background: #6ee823;\n"
"}\n"
"\n"
"#checkButton:hover{\n"
"    background: #7abf4e;\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"#checkButton:pressed{\n"
"    background: #718565;\n"
"}")
        self.checkButton.setObjectName("checkButton")
        self.horizontalLayout.addWidget(self.checkButton)
        self.runButton = QtWidgets.QPushButton(self.centralwidget)
        self.runButton.setStyleSheet("#runButton{\n"
"    color:white;\n"
"    font-weight: bold;\n"
"    background: black;\n"
"}\n"
"\n"
"#runButton:hover{\n"
"    background: #858585;\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"#runButton:pressed{\n"
"    background: #718565;\n"
"}")
        self.runButton.setObjectName("runButton")
        self.horizontalLayout.addWidget(self.runButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.textEdit = QsciScintilla()
        font = QtGui.QFont()
        font.setFamily('Courier')
        font.setFixedPitch(True)
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setMarginsFont(font)

        fontmetrics = QtGui.QFontMetrics(font)
        self.textEdit.setMarginsFont(font)
        self.textEdit.setMarginWidth(0, fontmetrics.width("00000") + 6)
        self.textEdit.setMarginLineNumbers(0, True)
        self.textEdit.setMarginsBackgroundColor(QtGui.QColor("#cccccc"))

        self.textEdit.setMarginSensitivity(1, True)
        self.textEdit.markerDefine(QsciScintilla.RightArrow,
                                   self.textEdit.SC_MARK_ARROW)
        self.textEdit.setMarkerBackgroundColor(QtGui.QColor("#ee1111"),
                                               self.textEdit.SC_MARK_ARROW)

        self.textEdit.setBraceMatching(QsciScintilla.SloppyBraceMatch)
        self.textEdit.setCaretLineVisible(True)
        self.textEdit.setCaretLineBackgroundColor(QtGui.QColor("#ffe4e4"))

        lexer = QsciLexerPython()
        lexer.setDefaultFont(font)
        self.textEdit.setLexer(lexer)

        text = bytearray(str.encode("Arial"))
        self.textEdit.SendScintilla(QsciScintilla.SCI_STYLESETFONT, 1, text)
        self.textEdit.SendScintilla(QsciScintilla.SCI_SETHSCROLLBAR, 0)

        self.textEdit.setMinimumSize(600, 450)
        self.textEdit.setTabWidth(4)
        self.verticalLayout.addWidget(self.textEdit)

        """
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setMinimumSize(QtCore.QSize(0, 250))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setStyleSheet("background-color: #1D1B20;\n"
"color: white;")
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout.addWidget(self.textEdit_2)
        """
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background-color: #1D1B20 ")
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Задание"))
        self.label_2.setText(_translate("MainWindow", "Пиши код сюда"))
        self.checkButton.setText(_translate("MainWindow", "Проверить"))
        self.runButton.setText(_translate("MainWindow", "Запустить код"))
        self.label_3.setText(_translate("MainWindow", "Результат"))
